import 'package:eslamy/Home/quran/vers_name.dart';
import 'package:flutter/material.dart';

class Quran_tab extends StatelessWidget {
  List<String> Names = [
    "الفاتحه",
    "البقرة",
    "آل عمران",
    "النساء",
    "المائدة",
    "الأنعام",
    "الأعراف",
    "الأنفال",
    "التوبة",
    "يونس",
    "هود",
    "يوسف",
    "الرعد",
    "إبراهيم",
    "الحجر",
    "النحل",
    "الإسراء",
    "الكهف",
    "مريم",
    "طه",
    "الأنبياء",
    "الحج",
    "المؤمنون",
    "النّور",
    "الفرقان",
    "الشعراء",
    "النّمل",
    "القصص",
    "العنكبوت",
    "الرّوم",
    "لقمان",
    "السجدة",
    "الأحزاب",
    "سبأ",
    "فاطر",
    "يس",
    "الصافات",
    "ص",
    "الزمر",
    "غافر",
    "فصّلت",
    "الشورى",
    "الزخرف",
    "الدّخان",
    "الجاثية",
    "الأحقاف",
    "محمد",
    "الفتح",
    "الحجرات",
    "ق",
    "الذاريات",
    "الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "الطلاق",
    "التحريم",
    "الملك",
    "القلم",
    "الحاقة",
    "المعارج",
    "نوح",
    "الجن",
    "المزّمّل",
    "المدّثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "النبأ",
    "النازعات",
    "عبس",
    "التكوير",
    "الإنفطار",
    "المطفّفين",
    "الإنشقاق",
    "البروج",
    "الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العاديات",
    "القارعة",
    "التكاثر",
    "العصر",
    "الهمزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس"
  ];

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Expanded(
            flex: 1, child: Image.asset("assets/images/quran_tab_logo.png")),
        Container(
          margin: EdgeInsets.only(top: 3, bottom: 3),
          width: double.infinity,
          color: Theme.of(context).primaryColor,
          height: 3,
        ),
        Text("Sura Name", style: TextStyle(fontSize: 26)),
        Container(
          margin: EdgeInsets.only(top: 3, bottom: 3),
          width: double.infinity,
          color: Theme.of(context).primaryColor,
          height: 2,
        ),
        Expanded(
            flex: 3,
            child: ListView.separated(
              itemBuilder: (context, index) {
                return VersNameWidget(index: index, title: Names[index]);
              },
              itemCount: Names.length,
              separatorBuilder: (context, index) {
                return Container(
                  width: double.infinity,
                  color: Theme.of(context).primaryColor,
                  height: 1.5,
                  margin: EdgeInsets.symmetric(horizontal: 24),
                );
              },
            ))
      ],
    );
  }
}
